//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using AssemblyCSharpfirstpass;


public class Data{

	public string Name = "";
	public string Unit = "";
	public string UseMin = "";
	public string UseMax = "";
	public string Precision = "";


	public Data (){
	}


	public Data (Data d){
		Name = d.Name;
		Unit = d.Unit;
		UseMin = d.UseMin;
		UseMax = d.UseMax;
		Precision = d.Precision;
	}

	public Data(string s){
		Name = PString.ReadArg("Name",s);
		Unit = PString.ReadArg("Unit",s);
		UseMin = PString.ReadArg("UseMin",s);
		UseMax = PString.ReadArg("UseMax",s);
		Precision = PString.ReadArg("Precision",s);
		
	}



	public string ToString(){
		return 
				PString.WriteArg("Name",Name) + 
				PString.WriteArg("Unit",Unit) + 
				PString.WriteArg("UseMin",UseMin) + 
				PString.WriteArg("UseMax",UseMax) + 
				PString.WriteArg("Precision",Precision);
	}

	public static Data[] Add( Data[] da, Data d){
		Data[] res = new Data[da.Length+1];
		for(int i = 0; i < da.Length ; i++){
			res[i] = new Data (da[i]);
		}
		res[da.Length] = new Data(d);
		return res;
	}

	public static Data[] Remove( Data[] da, int index){
		if (index >= da.Length)
			return da;

		Data[] res = new Data[da.Length-1];
		int offset = 0;
		for(int i = 0; i < da.Length ; i++){
			if(i == index){
				offset = -1;
				continue;
			}
			res[i+offset] = new Data (da[i]);
		}
		return res;
	}



}

