//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace AssemblyCSharpfirstpass
{
	public class LabelAndBoolean{

		public string Label;
		public bool Value;

		public LabelAndBoolean (string l, bool b){
			Label = l;
			Value = b;
		}


		public static bool GetValue(LinkedList<LabelAndBoolean> list, string s){
			foreach(LabelAndBoolean lab in list){
				if(lab.Label == s){
					return lab.Value;
				}
			}
			return false;
		}
	}

}

