//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

public class StaticMemory{
	public static bool RunFirstTime = true;
	public static Texture A4HTexture;

	public static LinkedList<SensorAndFunction> SensorCfgList= new LinkedList<SensorAndFunction>();
	public static LinkedList<Geoloc> RoomList= new LinkedList<Geoloc>();
	public static LinkedList<Sensor> SensorList = new LinkedList<Sensor>();

	public static bool LoadRoomList = false;
	public static bool LoadSensorList = false;
	public static bool LoadSensorCfgList = true;
	public static string LoadSensorPath = "";

	public static bool SaveRoomList = false;

	
	public static int SensorCount = 0;
	public static float Step = 1f;


		
	//public static string CurrentPreSelectedBuildingPath = "D:/Data/Buildings/Domus";
	public static string CurrentPreSelectedBuildingPath = "D:/Data/Buildings/OpenHabDemo";
	public static string CurrentPath = "D:/Data";


	public static string LoadVirtualSensor = "Void";
	public static string SaveVirtualSensor = "Autosave";

	public static string URL = "http://localhost:8080";
	public static string RootNameItem = "";
	public static string[] ArrayofOBJ = new string[0];
	public static bool[] ArrayofOBJBool = new bool[0];



	public static int _SizeX = 1000;
	public static int _SizeY = 700;
	public static int _Margin = 20;
	public static int _Caption = 50;
	public static int _hauteurChamp = 23;
	public static int _hauteurEntre = 10;

}

