//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace AssemblyCSharpfirstpass {

	public class ParseString {
		private string OP1 = "";
		private string OP2 = "";





		public ParseString (){
				}

	
	
		static public string[] SplitFirst (string s, char sep){
			string[] res = new string[2];
			string[] val = s.Split(sep);
			
			res[0] = val[0];
			res[1] = "";
			for (int i = 1; i<val.Length; i++){
				if(i == 1){
					res[1]+= val[i];
				}
				else{
					res[1]+= sep + val[i];
				}
			}
			
			if(val.Length == 1){
				res[1] = "";
			}
			return res;
		}

		static public string SuprFirst (string s, char sep){
			string[] res = new string[2];
			string[] val = s.Split(sep);
			
			res[0] = val[0];
			res[1] = "" + sep;
			for (int i = 1; i<val.Length; i++){
				if(i == 1){
					res[1]+= val[i];
				}
				else{
					res[1]+= sep + val[i];
				}
			}
			
			if(val.Length == 1){
				res[1] = "";
			}
			return res[0] + res[1];
		}


		static public string RemplaceFlag(string source, LinkedList<string[]> keys){
			foreach(String[] val in keys){
				source = source.Replace(val[0], val[1]);
			}
			return source;
		}


}
}

